spring:
    profiles.active: development, development-api

# development profile section
---
spring:
    profiles: development
    
    datasource:
        url: jdbc:h2:~/pointcoindb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        test-while-idle: true
        validation-query: SELECT 1
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        generate-ddl: true

pointcoin:
    wallet:
        rpc-url: http://10.30.158.23:9332
        rpc-user: admin
        rpc-password: 123456         
    task:
        deposit-record-push:
            cron: 0 0/15 * 1/1 * ?
       
endpoints:
    health:
        sensitive: false
        enabled: true
    actuator:
        enabled: true

# production profile section
---
spring:
    profiles: production
    
pointcoin:
    wallet:
        alias: default
        rpc-url: http://127.0.0.1:8332

# default profile section
---
spring:
    jpa:
        show-sql: true

 