spring:
    profiles.active: development

################################  
# development profile section  #
################################

---
spring:
    profiles: development
    
    datasource:
        url: jdbc:h2:~/pointcoindb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        test-while-idle: true
        validation-query: SELECT 1
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        generate-ddl: true

pointcoin:
    wallet:
        alias: default
        rpc-url: http://10.30.158.23:9332
        rpc-user: admin
        rpc-password: 123456      

    security:
        allowip: 127.0.0.1;10.0.0.0/8;192.0.0.0/8
        users:
          -
            name: admin
            password: 123456
            roles:
              - ADMIN
              - USER
              - PARTNER

endpoints:
    health:
        sensitive: false
        enabled: true
    actuator:
        enabled: true


###############################
# test profile section  #
###############################

---
spring:
    profiles: test

    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://${POINTCOIN_MQSQL_HOST:${MYSQL_PORT_3306_TCP_ADDR:127.0.0.1}}:${POINTCOIN_MQSQL_PORT:${MYSQL_PORT_3306_TCP_PORT:3306}}/${POINTCOIN_MQSQL_DATABASE:${MYSQL_ENV_MYSQL_DATABASE:pointcoindb}}?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: ${POINTCOIN_MQSQL_USER:${MYSQL_ENV_MYSQL_USER:pointcoinapiremote}}
        password: ${POINTCOIN_MQSQL_PASSWORD:${MYSQL_ENV_MYSQL_PASSWORD:Rdisfun4pointcoinapiremote}}

        #连接池的配置信息
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat,wall,log4j
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        generate-ddl: true


###############################     
# production profile section  #
###############################

---
spring:
    profiles: production
    
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://${POINTCOIN_MQSQL_HOST:${MYSQL_PORT_3306_TCP_ADDR:127.0.0.1}}:${POINTCOIN_MQSQL_PORT:${MYSQL_PORT_3306_TCP_PORT:3306}}/${POINTCOIN_MQSQL_DATABASE:${MYSQL_ENV_MYSQL_DATABASE:pointcoindb}}?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: ${POINTCOIN_MQSQL_USER:${MYSQL_ENV_MYSQL_USER:pointcoinapiremote}}
        password: ${POINTCOIN_MQSQL_PASSWORD:${MYSQL_ENV_MYSQL_PASSWORD:Rdisfun4pointcoinapiremote}}
        
        #连接池的配置信息
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat,wall,log4j
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000        
        
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        generate-ddl: true   

###########################
# default profile section #
###########################
---        
logging:
    config: classpath:pointcoin-logback.xml
    level:
        com.upbchain: DEBUG

jasypt:
    encryptor:
        password: ${JASYPT_ENCRYPTOR_PASSWORD:}

pointcoin:
    wallet:
        kind: ${POINTCOIN_WALLET_RPC_KIND:${WALLET_KIND:pointcoin}}
        alias: ${POINTCOIN_WALLET_RPC_ALIAS:${WALLET_ALIAS:default}}
        rpc-url: ${POINTCOIN_WALLET_RPC_URL:http://127.0.0.1:22888}
        rpc-user: ${POINTCOIN_WALLET_RPC_USER:pointcoinrpc}
        rpc-password: ${POINTCOIN_WALLET_RPC_PASSWORD:123456}

    task:
        deposit-record-push:
            cron: ${POINTCOIN_TASK_DR_PUSH_CRON:0 0/5 * 1/1 * ?}
            url: ${POINTCOIN_TASK_DR_PUSH_URL:http://127.0.0.1:8080/api/echo}
            username: ${POINTCOIN_TASK_DR_PUSH_USER:}
            password: ${POINTCOIN_TASK_DR_PUSH_PASSWORD:}

    security:
        allowip: ${POINTCOIN_SECURITY_ALLOWIP:127.0.0.1}
        users:
            -
                name: partner
                password: ${POINTCOIN_SECURITY_PARTNER_PASSWORD:123456}
                roles:
                    - PARTNER
            -
                name: user
                password: ${POINTCOIN_SECURITY_USER_PASSWORD:123456}
                roles:
                    - USER
                    - PARTNER
            -
                name: admin
                password: ${POINTCOIN_SECURITY_ADMIN_PASSWORD:123456}
                roles:
                    - PARTNER
                    - USER
                    - ADMIN
spring:
    jpa:
        hibernate:
            ddl-auto: update
 